### ISSUE TITLE
[Android Course] Project 0: Todo - Ready for Review

### ISSUE THREAD

**Issue by kristeaac** [kristeaac/codepath-project-0-todo#1]
My app is complete. Please review. /cc @codepathreview @codepath

I would like some feedback about best practices for styling an app both in XML and programatically. I know some of what I did to make it work is the equivalent of inline CSS.

**Comment by nidhi1608** [comment]
:+1: Excellent work Kristy! This was intended in part to give you an introduction to the general rhythm of this course. The course is entirely project based with an app being assigned each week and then due the following week. Each project builds on the last to help each engineer to learn all practical Android development and best practices as quickly as possible. We also do a code review for each submitted project.
Nice job with the project, hope you found it as a helpful introduction.

Look forward to seeing you in the class!  

>I would like some feedback about best practices for styling an app both in XML and programatically. I know some of what I did to make it work is the equivalent of inline CSS.

Really impressed with what you have done so far, but as you mentioned, defining the styles per element is not always the best programming practice. Check out the guide on [Android Styles and Themes](http://guides.codepath.com/android/Styles-and-Themes) which is loosely identical to CSS classes. You can also externalize various resources  as specified in the guide [here](http://developer.android.com/guide/topics/resources/more-resources.html) so your code is more centralized and maintainable. We'll discuss these topics later in the class.

**Comment by kristeaac** [comment]
Thank you for taking the time to review and sharing the style guide!
